sudo: required
dist: trusty

before_script:
  # Configuring a virtual CAN bus interface for UAVCAN protocol testing
  - sudo modprobe can
  - sudo modprobe can_raw
  - sudo modprobe vcan
  - sudo ip link add dev kocherga0 type vcan
  - sudo ip link set up kocherga0
  - sudo ifconfig kocherga0 up
  # Installing dependencies for the YMODEM protocol test
  - sudo apt-get install lrzsz
  # Installing Python dependencies
  - sudo apt-get install python3-pip
  - sudo pip3 install "uavcan>=1.0.0.dev30"

matrix:
  include:
    #
    # GCC 7
    #
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            # We need i386 packages because we compile libcanard in 32-bit mode, it doesn't support 64-bit platforms.
            - g++-7
            - g++-7-multilib
            - gcc-7-multilib
            - linux-libc-dev:i386
      script:
        - CC=gcc-7 && CXX=g++-7 && cd test/ && cmake . && make
        - ./kocherga_test --rng-seed time

    #
    # Clang 5
    #
    - language: cpp
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            # We need i386 packages because we compile libcanard in 32-bit mode, it doesn't support 64-bit platforms.
            - clang-5.0
            - libstdc++-7-dev:i386   # This package contains the C++ standard library used by Clang-5.0
            - linux-libc-dev:i386
            - libc6-dev-i386
      script:
        - clang++-5.0 -E -x c++ - -v < /dev/null    # Print the Clang configuration for troubleshooting purposes
        - cd test/
        - cmake -DCMAKE_C_COMPILER=clang-5.0 -DCMAKE_CXX_COMPILER=clang++-5.0 .
        - make
        - ./kocherga_test --rng-seed time
